resources:
  repositories:
    - repository: self

pr:
  autoCancel: false
  branches:
    include:
      - master
      - release/*

variables:
  pathToTheProjectFile: '$(Build.SourcesDirectory)/src/Qala.Cli/Qala.Cli.csproj' 
  pathToTheProjectTestFile: '$(Build.SourcesDirectory)/tests/Qala.Cli.Integration.Tests/Qala.Cli.Integration.Tests.csproj' 
  runtimeIdentifiers: 'win-x64;win-arm64;linux-x64;osx-arm64'
 
pool:
  vmImage: ubuntu-latest

stages:
# Stage Build and Test (only for PRs from feature and hotfix branches)
- stage: BuildAndTest
  displayName: "Build and Test"
  jobs:
  # Build and Test
  - job: BuildAndTest
    displayName: "Build and Test"
    strategy:
      matrix:
        Windows:
          vmImage: 'windows-latest'
          runtimeIdentifiers: 'win-x64;win-arm64'
        Linux:
          vmImage: 'ubuntu-latest'
          runtimeIdentifiers: 'linux-x64'
        macOS:
          vmImage: 'macOS-latest'
          runtimeIdentifiers: 'osx-arm64'
    steps:
    # Install SDK Using global.json
    - task: UseDotNet@2
      displayName: 'Install SDK Using global.json'
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: $(Pipeline.Workspace)/s

    # Restore NuGet Packages
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    # Build the project
    - task: DotNetCoreCLI@2
      displayName: 'Build the project'
      inputs:
        command: 'build'
        projects: '$(pathToTheProjectFile)'

    # Run tests
    - task: DotNetCoreCLI@2
      displayName: 'Run tests'
      inputs:
        command: 'test'
        projects: '$(pathToTheProjectTestFile)'
