resources:
  repositories:
    - repository: self

trigger:
  branches:
    include:
      - release/*
  paths:
    include:
      - src/Qala.Cli.Data
      - src/Qala.Cli

pr:
  autoCancel: false
  branches:
    include:
      - master
  paths:
    exclude:
      - tests/*

variables:
  pathToTheProjectFile: '$(Build.SourcesDirectory)/src/Qala.Cli/Qala.Cli.csproj' 
  pathToTheProjectTestFile: '$(Build.SourcesDirectory)/tests/Qala.Cli.Integration.Tests/Qala.Cli.Integration.Tests.csproj' 
  major: 1
  minor: 0
  patch: $[counter(variables['major'], 0)]
  runtimeIdentifiers: 'win-x64;win-arm64;linux-x64;osx-arm64'
  gitHubConnection: 'github.com_tvcosta'
  repositoryName: 'QalaTech/qala-cli'
  alphaVersion: ''
  releaseVersion: ''

pool:
  vmImage: ubuntu-latest

stages:
# Stage Alpha Build And Publish (only for merged from hotfix to release branches and feature to master branches)
- stage: Alpha
  # condition: and(succeeded(), or(and(eq(variables['Build.Reason'], 'PullRequest'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))), and(eq(variables['Build.Reason'], 'Manual'), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/master')))))
  displayName: "Build and Publish Alpha Version"
  jobs:
  # Build and Publish Alpha Executables and Installers
  - job: BuildAndPublishAlpha
    displayName: "Build and Publish Alpha Executables and Installers"
    strategy:
      matrix:
        Windows:
          vmImage: 'windows-latest'
          runtimeIdentifiers: 'win-x64;win-arm64'
        # Linux:
        #   vmImage: 'ubuntu-latest'
        #   runtimeIdentifiers: 'linux-x64'
        # macOS:
        #   vmImage: 'macOS-latest'
        #   runtimeIdentifiers: 'osx-arm64'
    pool: 
      vmImage: '$(vmImage)'
    steps:
    # Set Alpha Version Number
    - task: PowerShell@2
      displayName: 'Set Alpha Version Number'
      inputs:
        targetType: 'inline'
        script: |
          # Fetch the previous version from a file or a variable
          $previousVersion = "$(major).$(minor).$(patch)" # Default value if no previous version is found
          if (Test-Path "$(Build.ArtifactStagingDirectory)/previousVersion.txt") {
            $previousVersion = Get-Content "$(Build.ArtifactStagingDirectory)/currentVersion.txt"
          }

          # Split the previous version into major, minor, and patch
          $versionParts = $previousVersion -split '\.'
          $major = [int]$versionParts[0]
          $minor = [int]$versionParts[1]
          $patch = [int]$versionParts[2]

          # Determine if the branch name starts with hotfix or HOTFIX
          if ($env:BUILD_SOURCEBRANCHNAME -match '^hotfix' -or $env:BUILD_SOURCEBRANCHNAME -match '^HOTFIX') {
            # Increment the patch version
            $patch++
          } else {
            # Increment the minor version
            $minor++
          }

          # Set the alpha version
          $alphaVersion = "v$major.$minor.$patch-alpha.$env:BUILD_BUILDID"
          Write-Host "##vso[task.setvariable variable=alphaVersion]$alphaVersion"
          Write-Host "Alpha Version: $alphaVersion"

          # Save the new version to a file for future reference
          $newVersion = "$major.$minor.$patch"
          Set-Content -Path "$(Build.ArtifactStagingDirectory)/currentVersion.txt" -Value $newVersion
    
    # Restore NuGet Packages
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    # Build and publish Alpha executables
    - task: PowerShell@2
      displayName: 'Build and publish Alpha executables'
      inputs:
        targetType: 'inline'
        workingDirectory: $(Build.SourcesDirectory)/src/Qala.Cli
        script: |
          $runtimeIdentifiers = "$(runtimeIdentifiers)".Split(";")
          # Check if the pathToTheProjectFile file exists
          if (Test-Path $(pathToTheProjectFile)) {
              Write-Host "Qala.Cli.csproj file found."
          } else {
              Write-Host "Qala.Cli.csproj file not found."
              exit 1
          }
          foreach ($rid in $runtimeIdentifiers) {
            Write-Host "Publishing Alpha version for runtime: $rid"
            dotnet publish $(pathToTheProjectFile) -r $rid --self-contained true -p:PublishSingleFile=true -o "$(Pipeline.Workspace)/alpha/$rid"
          }

    # If Windows, install WiX Toolset and UI extensions
    - task: PowerShell@2
      displayName: 'Install WiX Toolset and UI extensions'
      condition: eq('$(vmImage)', 'windows-latest')
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        targetType: 'inline'
        script: |
          dotnet tool install --global wix
          wix extension add WixToolset.UI.wixext

    # If Windows, create installers for each runtime identifiers
    - task: PowerShell@2
      displayName: 'Create installers for each runtime identifiers'
      condition: eq('$(vmImage)', 'windows-latest')
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        targetType: 'inline'
        script: |
          $runtimeIdentifiers = "$(runtimeIdentifiers)".Split(";")
          foreach ($rid in $runtimeIdentifiers) {
            Write-Host "Generating the msi file for runtime: $rid"
            wix build wix/qala.wxs -d Version=$VERSION -ext WixToolset.UI.wixext -o "QalaCliInstaller--$(alphaVersion)-$rid.msi"
          }

    # If Windows, move all installers and executables to the artifact staging directory
    - task: PowerShell@2
      displayName: 'Move all installers and executables to the artifact staging directory'
      condition: eq('$(vmImage)', 'windows-latest')
      inputs:
        targetType: 'inline'
        script: |
          $runtimeIdentifiers = "$(runtimeIdentifiers)".Split(";")
          foreach ($rid in $runtimeIdentifiers) {
            Write-Host "Moving installer and executables for runtime: $rid"
            Move-Item -Path "$(Pipeline.Workspace)/alpha/$rid/wix/QalaCliInstaller-$(alphaVersion)-$rid.msi" -Destination "$(Build.ArtifactStagingDirectory)/alpha/$rid" -Force
            Move-Item -Path "$(Pipeline.Workspace)/alpha/$rid/qala.exe" -Destination "$(Build.ArtifactStagingDirectory)/alpha/$rid" -Force
          }

    # If Windows, create GitHub Alpha Release
    - task: GithubRelease@1 
      displayName: 'Create GitHub Alpha Release'
      condition: eq('$(vmImage)', 'windows-latest')     
      inputs:
        gitHubConnection: '$(gitHubConnection)'
        repositoryName: '$(repositoryName)'
        target: '$(Build.SourceBranchName)'
        tagSource: 'userSpecifiedTag'
        tag: "$(alphaVersion)"
        isPreRelease: true
        title: 'Alpha Release $(alphaVersion)'   
        assets: $(Build.ArtifactStagingDirectory)/alpha/*