Auth:
  URL: "https://dev-lqwdwo2zdrq7ygsg.us.auth0.com"
  ClientID: "gv2q0aAxsQ1mezQtZ4ao9DJjGOYFeybB"
  Audience: "https://management-api.blackpond-239b58cc.northeurope.azurecontainerapps.io/"

Management-API:
  URL: "https://management-api.blackpond-239b58cc.northeurope.azurecontainerapps.io/v1/"